apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simplemicroservice
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: simplemicroservice.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simplemicroservice
                port:
                  number: 8080
